//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeedzDrive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeedzDrive.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seedz Drive.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the credential provided by seedz..
        /// </summary>
        public static string ConfigurationWindowClientIdTextbox {
            get {
                return ResourceManager.GetString("ConfigurationWindowClientIdTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to sync..
        /// </summary>
        public static string ConfigurationWindowFolderTextbox {
            get {
                return ResourceManager.GetString("ConfigurationWindowFolderTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConfigurationWindowSaveButton {
            get {
                return ResourceManager.GetString("ConfigurationWindowSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Saved.
        /// </summary>
        public static string ConfigurationWindowSavedMessage {
            get {
                return ResourceManager.GetString("ConfigurationWindowSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the credential provided by seedz..
        /// </summary>
        public static string ConfigurationWindowSecretTextbox {
            get {
                return ResourceManager.GetString("ConfigurationWindowSecretTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string ConfigurationWindowSelectFolderButton {
            get {
                return ResourceManager.GetString("ConfigurationWindowSelectFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder.
        /// </summary>
        public static string ConfigurationWindowSelectFolderDialogTitle {
            get {
                return ResourceManager.GetString("ConfigurationWindowSelectFolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string ConfigurationWindowSelectFolderLabel {
            get {
                return ResourceManager.GetString("ConfigurationWindowSelectFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seedz Drive - Configuration.
        /// </summary>
        public static string ConfigurationWindowTitle {
            get {
                return ResourceManager.GetString("ConfigurationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is syncing....
        /// </summary>
        public static string NotifyIconBaloomTextSync {
            get {
                return ResourceManager.GetString("NotifyIconBaloomTextSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seedz Drive is running in background.
        /// </summary>
        public static string NotifyIconBaloomTitle {
            get {
                return ResourceManager.GetString("NotifyIconBaloomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string NotifyIconMenuClose {
            get {
                return ResourceManager.GetString("NotifyIconMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string NotifyIconMenuConfiguration {
            get {
                return ResourceManager.GetString("NotifyIconMenuConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string NotifyIconMenuLogs {
            get {
                return ResourceManager.GetString("NotifyIconMenuLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        public static string NotifyIconMenuOpenFolder {
            get {
                return ResourceManager.GetString("NotifyIconMenuOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was not uploaded because it is larger than 10MB..
        /// </summary>
        public static string NotUploadedBecauseLarger {
            get {
                return ResourceManager.GetString("NotUploadedBecauseLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload complete..
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
    }
}
